Unblock wallaby gate
This is a combination of 2 commits that both needed to unblock
stable/wallaby gate:

1. Remove contradictions in lower-constraints

This will avoid the following issue seen recently on wallaby and on
projects where lower-constraints tests haven't been yet dropped:

```
ERROR: Could not find a version that satisfies the requirement
bandit<1.7.0,>=1.6.0
ERROR: No matching distribution found for bandit<1.7.0,>=1.6.0
```

Also some other packages lower constraints has to bump to avoid
further contradictions and slow run of the pip resolver.

2. move flake8 as a pre-commit local target

The goal here is to avoid conflicts between flake8 and hacking version each
2 days.

Inspired from nova's approach [1].

The flake8 version to install will be determined by hacking and
requirements will stay aligned instead of relying on different versions.

[1] https://opendev.org/openstack/nova/src/branch/master/.pre-commit-config.yaml#L26-L35
[2] https://opendev.org/openstack/hacking/src/branch/master/requirements.txt#L1

Conflicts:
    pre-commit-config.yaml

(NOTE) hberaud: Original commit was made on the top of intermediary
changes on master.

Change-Id: Iae20f13ba6293b94b5bd131941263e097eba0518
(cherry picked from commit 7443bcd079e1c52e8527b5f4b9ce1431aa7cf317)